### ISSUE TITLE
ViewBinding初始化失败

### ISSUE THREAD

**Issue by chenmingyin** [Quyunshuo/AndroidBaseFrameMVVM#24]
Android 13
在Android Studio的模拟器上运行APP，正常的页面也会随机出现ViewBinding初始化失败，有时候正常运行，有时候出现异常。
报错内容：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.xxx.main.mvvm.view.MainPageAct}: java.lang.RuntimeException: ViewBinding初始化失败
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  定位到基类，发现是这一段代码有问题，
fun <V : ViewBinding> reflexViewBinding(aClass: Class<*>, from: LayoutInflater?): V {
        try {
            val actualTypeArguments =
                (Objects.requireNonNull(aClass.genericSuperclass) as ParameterizedType).actualTypeArguments
            for (i in actualTypeArguments.indices) {
                val tClass: Class<Any>
                try {
                    tClass = actualTypeArguments[i] as Class<Any>
                } catch (e: Exception) {
                    continue
                }
                if (ViewBinding::class.java.isAssignableFrom(tClass)) {
                    val inflate = tClass.getMethod("inflate", LayoutInflater::class.java)
                    return inflate.invoke(null, from) as V
                }
            }
            return reflexViewBinding<V>(aClass.superclass, from)
        } catch (e: NoSuchMethodException) {
            e.printStackTrace()
        } catch (e: IllegalAccessException) {
            e.printStackTrace()
        } catch (e: InvocationTargetException) {
            e.printStackTrace()
        }
        throw RuntimeException("ViewBinding初始化失败")
    }
，也就是运行到这个方法时候，不知道为啥，直接throw RuntimeException("ViewBinding初始化失败")了。

求大佬指点一下。

**Comment by chenmingyin** [comment]
我的ViewBinding版本是7.3.1，androidx.databinding:viewbinding:7.3.1@aar

**Comment by Quyunshuo** [comment]
项目有没有开启代码压缩混淆

**Comment by chenmingyin** [comment]
没有

**Comment by chenmingyin** [comment]
const val compileSdkVersion = 33
 const val buildToolsVersion = "33.0.1"
const val minSdkVersion = 21
const val targetSdkVersion = 33

**Comment by Quyunshuo** [comment]
这样，你先打个断点看下具体走的哪个异常，看一下堆栈信息

**Comment by chenmingyin** [comment]
走的是这个异常，
`catch (e: InvocationTargetException) {
            e.printStackTrace()
        }`
堆栈里面的detailMessage:
Binary XML file line #26 in com.xxx.xxx:layout/main_act_main_page: Binary XML file line #26 in com.xxx.xxx:layout/main_act_main_page: Error inflating class com.coorchice.library.SuperTextView

虽然报这个错误，但是实际上这个控件的使用时没问题的，在7.0这些低版本上都是正常运行的。

**Comment by Quyunshuo** [comment]
自定义view的问题吧，构造函数都正确重写了吗

**Comment by chenmingyin** [comment]
我刚才去这个自定义View的项目里看了，https://github.com/chenBingX/SuperTextView，这个控件只提供了x86的系统镜像，而AndroidStudio的模拟器在Android 12、13上只能使用x86_64的系统镜像，所以有可能是这个原因导致这个自定义View在x86_64的模拟器上时而能用，时而报错。

**Comment by Quyunshuo** [comment]
> 我刚才去这个自定义View的项目里看了，https://github.com/chenBingX/SuperTextView，这个控件只提供了x86的系统镜像，而AndroidStudio的模拟器在Android 12、13上只能使用x86_64的系统镜像，所以有可能是这个原因导致这个自定义View在x86_64的模拟器上时而能用，时而报错。

这个你可以进一步验证下，如果排除这个原因还是有问题，你再联系我
